import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {createProviderPushManager,renderProviderPushSettings} from '../src/provider/provider-push.js';
import {VAPID_PUBLIC_KEY as publicKey} from '../supabase/functions/_shared/provider-push-config.js';
const makeEnv=({standalone=true,permission='default'}={})=>{
  const store=new Map();let permissionCalls=0;const subscription={endpoint:'https://push.example/subscription',toJSON:()=>({endpoint:'https://push.example/subscription',keys:{p256dh:'p'.repeat(40),auth:'a'.repeat(20)}})};
  const listeners=new Map();const environment={isSecureContext:true,PushManager:function(){},crypto:{randomUUID:()=> '11111111-1111-4111-8111-111111111111'},localStorage:{getItem:k=>store.get(k)??null,setItem:(k,v)=>store.set(k,v)},matchMedia:()=>({matches:standalone}),Notification:{permission,requestPermission:async()=>{permissionCalls++;environment.Notification.permission='granted';return 'granted';}},navigator:{serviceWorker:{ready:Promise.resolve({pushManager:{getSubscription:async()=>null,subscribe:async options=>{assert.equal(options.userVisibleOnly,true);return subscription;}}})}},document:{visibilityState:'visible',addEventListener:(n,f)=>listeners.set(n,f),removeEventListener:()=>{}},location:{href:'https://example.com/Home-ai/provider/'},history:{replaceState(){}},setInterval:()=>1,clearInterval(){}};
  return {environment,permissionCalls:()=>permissionCalls};
};
test('Provider enables notifications only from an explicit action and registers its device once',async()=>{const calls=[];const env=makeEnv();const manager=createProviderPushManager({environment:env.environment,vapidPublicKey:publicKey,repository:{registerPush:async value=>calls.push(value),touchPush:async()=>{}}});assert.match(renderProviderPushSettings(await manager.state()),/Chưa bật/);assert.equal(env.permissionCalls(),0);const state=await manager.enable();assert.equal(state.status,'enabled');assert.equal(env.permissionCalls(),1);assert.equal(calls.length,1);assert.equal(calls[0].endpoint,'https://push.example/subscription');});
test('iPhone browser page explains Home Screen installation without requesting permission',async()=>{const env=makeEnv({standalone:false});const manager=createProviderPushManager({environment:env.environment,vapidPublicKey:publicKey,repository:{}});const state=await manager.enable();assert.match(state.message,/Màn hình chính/);assert.equal(env.permissionCalls(),0);});
test('permission refusal and unsupported clients expose a clear non-enabled state',async()=>{const env=makeEnv();env.environment.Notification.requestPermission=async()=> 'denied';assert.equal((await createProviderPushManager({environment:env.environment,vapidPublicKey:publicKey,repository:{}}).enable()).status,'denied');assert.match(renderProviderPushSettings({status:'denied'}),/Bị từ chối/);});
test('push presence is touched on lifecycle changes without a periodic database timer',()=>{const env=makeEnv();let touches=0;env.environment.setInterval=()=>assert.fail('No periodic push touch');const manager=createProviderPushManager({environment:env.environment,vapidPublicKey:publicKey,repository:{touchPush:async()=>{touches++;}}});manager.start();manager.start();assert.equal(touches,1);manager.stop();});
test('Service Worker uses an opaque reference, deduplicated notification tag and reloads truth after click',()=>{const source=readFileSync(new URL('../provider/provider-sw.js',import.meta.url),'utf8');assert.match(source,/addEventListener\('push'/);assert.match(source,/showNotification/);assert.match(source,/home-ai-offer-\$\{data\.offerRef\}/);assert.match(source,/notificationclick/);assert.match(source,/push_offer=/);for(const forbidden of ['phone','clientName','latitude','longitude','address'])assert.doesNotMatch(source,new RegExp(forbidden,'i'));});
