import assert from 'node:assert/strict';import{readFile}from'node:fs/promises';import{describe,it}from'node:test';
const migration=new URL('../supabase/migrations/20260902000800_provider_diagnosis_and_quotes.sql',import.meta.url);
describe('sécurité SQL diagnostic et devis',()=>{
 it('lie la création au provider assigné actif et vérifié',async()=>{const sql=await readFile(migration,'utf8');assert.match(sql,/mission_row\.provider_id is distinct from uid/);assert.match(sql,/profile_has_role\(uid,'provider'\)/);assert.equal((sql.match(/pp\.active and pp\.kyc_status='verified'/g)??[]).length,2);assert.doesNotMatch(sql,/service_role|assigned_provider_id/);});
 it('impose arrived au premier devis et versionne après refus ou acceptation',async()=>{const sql=await readFile(migration,'utf8');assert.match(sql,/mission_row\.status<>'arrived'/);assert.match(sql,/parent_row\.status<>'accepted'/);assert.equal((sql.match(/max\(q\.version\),0\)\+1/g)??[]).length,2);assert.match(sql,/type='initial' and version>0 and parent_quote_id is null/);assert.doesNotMatch(sql,/update public\.quotes set diagnosis|update public\.quote_items/);});
 it('réserve acceptation et refus au client propriétaire sans démarrer avant acceptation',async()=>{const sql=await readFile(migration,'utf8');assert.match(sql,/mission_row\.client_id is distinct from uid/);assert.match(sql,/new_decision not in \('accepted','declined'\)/);assert.match(sql,/when quote_row\.type='initial' then 'declined'/);assert.match(sql,/when new_decision='accepted' then 'in_progress'/);assert.match(sql,/when quote_row\.type='initial' then 'arrived'/);assert.match(sql,/started_at=case when new_decision='accepted'/);});
 it('verrouille mission puis devis et revalide contre double décision',async()=>{const sql=await readFile(migration,'utf8');const missionLock=sql.indexOf('where id=locked_mission_id for update');const quoteLock=sql.indexOf('where id=target_quote_id for update');assert.ok(missionLock>0&&quoteLock>missionLock);assert.match(sql,/Quote is no longer awaiting acceptance/);});
 it('valide contenu, montants et garantit les RPC privées',async()=>{const sql=await readFile(migration,'utf8');assert.match(sql,/jsonb_array_length\(new_items\) not between 1 and 20/);assert.match(sql,/\(item->>'amount'\)::bigint < 0/);assert.equal((sql.match(/security definer set search_path = ''/g)??[]).length,3);assert.equal((sql.match(/from public,anon/g)??[]).length,3);assert.equal((sql.match(/to authenticated/g)??[]).length,3);assert.match(sql,/decide_current_customer_quote\(uuid,text\)/);});
 it('s’appuie sur les protections existantes des devis acceptés',async()=>{const secure=await readFile(new URL('../supabase/migrations/20260901000200_secure_home_ai_mvp_schema.sql',import.meta.url),'utf8');assert.match(secure,/An accepted quote is immutable; create a new quote version instead/);assert.match(secure,/Items of an accepted quote are immutable/);});
});
