import test from 'node:test';import assert from 'node:assert/strict';import {JSDOM} from 'jsdom';import {readFile} from 'node:fs/promises';
import {getProviderKycFileFormat,readProviderKycForm,renderProviderKyc,renderProviderKycProfileSection,validateProviderKycFile} from '../src/provider/provider-kyc.js';
import {createSupabaseOffersRepository} from '../src/supabase/repositories/offers.js';
import {validateProviderKycExtraction} from '../supabase/functions/_shared/provider-kyc-contract.ts';
import {initialiseProviderKycFlow,isProviderTestKycPreviewEnabled} from '../src/provider/provider-app.js';
import {detectProviderKycImageType} from '../supabase/functions/_shared/provider-kyc-image-signatures.ts';

const extraction={documentReadable:true,fields:{full_name:{value:'Nguyen Van A',confidence:.55},identity_number:{value:'123456789012',confidence:.99},date_of_birth:{value:'01/01/1990',confidence:.9},sex:{value:null,confidence:0},nationality:{value:'Viet Nam',confidence:.8},expiry_date:{value:null,confidence:0},address:{value:null,confidence:0}}};
test('valide extraction, valeurs absentes et faible confiance sans invention',()=>{const result=validateProviderKycExtraction(extraction);assert.equal(result.fields.sex.value,null);assert.equal(result.fields.full_name.confidence,.55);assert.equal(result.fields.expiry_date.value,null);});
test('un document illisible force tous les champs à null',()=>{const result=validateProviderKycExtraction({...extraction,documentReadable:false});for(const field of Object.values(result.fields))assert.deepEqual(field,{value:null,confidence:0});});
test('rend capture mobile, photothèque et formats iPhone HEIC/HEIF',()=>{const dom=new JSDOM(renderProviderKyc(null));const text=dom.window.document.body.textContent;assert.match(text,/Xác minh danh tính/);assert.match(text,/Chụp mặt trước CCCD/);assert.match(text,/Chụp ảnh/);assert.match(text,/Chọn từ thư viện/);assert.equal(dom.window.document.querySelectorAll('[data-provider-kyc-file]').length,2);assert.equal(dom.window.document.querySelector('[capture="environment"]')!==null,true);for(const input of dom.window.document.querySelectorAll('[data-provider-kyc-file]')){assert.match(input.accept,/image\/heic/);assert.match(input.accept,/image\/heif/);}});
test('valide JPEG PNG WebP HEIC et HEIF mobiles de moins de 8 Mo',()=>{for(const type of ['image/jpeg','image/png','image/webp','image/heic','image/heif','image/x-heic','image/x-heif'])assert.equal(validateProviderKycFile({size:100,type}),true);assert.deepEqual(getProviderKycFileFormat({type:'',name:'IMG_0123.HEIC'}),{extension:'heic',contentType:'image/heic'});assert.equal(validateProviderKycFile({size:9e6,type:'image/heic'}),false);assert.equal(validateProviderKycFile({size:100,type:'application/pdf',name:'card.pdf'}),false);});
test('reconnaît la signature HEIC/HEIF avant conversion serveur',()=>{const bytes=new Uint8Array([0,0,0,24,102,116,121,112,104,101,105,99,0,0,0,0,109,105,102,49]);assert.equal(detectProviderKycImageType(bytes),'heif');bytes[4]=0;assert.equal(detectProviderKycImageType(bytes),null);});
test('affiche les champs absents vides, signale une faible confiance et permet correction',()=>{const submission={id:'s1',status:'draft',extraction};const dom=new JSDOM(renderProviderKyc({submission},{stage:'confirm',previewUrl:'signed'}));const doc=dom.window.document;assert.match(doc.body.textContent,/Độ tin cậy thấp/);assert.equal(doc.querySelector('[name="sex"]').value,'');doc.querySelector('[name="full_name"]').value='Nguyễn Văn A';doc.querySelector('[name="address"]').value='Nha Trang';const result=readProviderKycForm(doc);assert.equal(result.valid,true);assert.equal(result.fields.full_name,'Nguyễn Văn A');assert.equal(result.fields.address,'Nha Trang');});
test('rend pending_review sans prétendre que l’identité est vérifiée',()=>{const html=renderProviderKyc({submission:{status:'pending_review'}});assert.match(html,/Hồ sơ của bạn đang được xác minh/);assert.doesNotMatch(html,/Đã xác minh/);});
test('affiche dans Hồ sơ les quatre statuts KYC et uniquement leurs actions autorisées',()=>{
  const draft=renderProviderKycProfileSection({provider:{kycStatus:'pending'},submission:null});assert.match(draft,/Chưa xác minh/);assert.match(draft,/Xác minh ngay/);
  const pending=renderProviderKycProfileSection({provider:{kycStatus:'pending'},submission:{status:'pending_review'}});assert.match(pending,/Đang xác minh/);assert.doesNotMatch(pending,/data-open-provider-kyc/);
  const verified=renderProviderKycProfileSection({provider:{kycStatus:'verified'},submission:{status:'verified'}});assert.match(verified,/✓ Đã xác minh/);assert.doesNotMatch(verified,/data-open-provider-kyc/);
  const rejected=renderProviderKycProfileSection({provider:{kycStatus:'rejected'},submission:{status:'rejected'}});assert.match(rejected,/Xác minh không thành công/);assert.match(rejected,/Thử lại/);
});
test('limite le bouton aperçu KYC au mode test et au Provider Test exact',()=>{const config={PROVIDER_TEST_MODE:true,PROVIDER_TEST_PROVIDER_ID:'2040840f-10c6-4acf-a800-1640e1520f4b'};const provider={id:'2040840f-10c6-4acf-a800-1640e1520f4b',name:'Provider Test Nha Trang'};assert.equal(isProviderTestKycPreviewEnabled(config,provider),true);assert.equal(isProviderTestKycPreviewEnabled(config,{...provider,id:'other'}),false);assert.equal(isProviderTestKycPreviewEnabled({...config,PROVIDER_TEST_MODE:false},provider),false);assert.match(renderProviderKycProfileSection({provider:{kycStatus:'verified'}},{testMode:true}),/TEST — Xem quy trình KYC/);assert.doesNotMatch(renderProviderKycProfileSection({provider:{kycStatus:'verified'}},{testMode:false}),/TEST/);});
test('correction manuelle puis confirmation passe uniquement à pending_review',async()=>{const dom=new JSDOM('<main id="root"></main>');const root=dom.window.document.querySelector('#root');let submitted;const state={provider:{id:'p1',kycStatus:'pending'},submission:{id:'s1',status:'draft',documentPath:'private',extraction}};await initialiseProviderKycFlow(root,{loadKyc:async()=>state,getIdentityPreview:async()=>'/signed-temporary',confirmKyc:async(id,fields)=>{submitted={id,fields};return{...state,submission:{...state.submission,status:'pending_review'}};}});root.querySelector('[name="full_name"]').value='Nguyễn Văn A';root.querySelector('[data-confirm-provider-kyc]').click();await new Promise(resolve=>setTimeout(resolve,0));assert.equal(submitted.id,'s1');assert.equal(submitted.fields.full_name,'Nguyễn Văn A');assert.match(root.textContent,/đang được xác minh/);assert.doesNotMatch(root.textContent,/Đã xác minh/);});
test('aperçu Provider Test analyse puis confirme sans Storage, RPC ni soumission persistante',async()=>{const dom=new JSDOM('<main id="root"></main>');const root=dom.window.document.querySelector('#root');let previews=0;let confirmations=0;const state={provider:{id:'2040840f-10c6-4acf-a800-1640e1520f4b',name:'Provider Test Nha Trang',kycStatus:'verified'},submission:null};await initialiseProviderKycFlow(root,{loadKyc:async()=>state,previewIdentity:async()=>{previews+=1;return{provider:state.provider,submission:{id:'test-preview',status:'draft',documentPath:null,extraction}};},confirmKyc:async()=>{confirmations+=1;}},{testMode:true,showBack:true});const input=root.querySelector('[data-provider-kyc-file]');Object.defineProperty(input,'files',{value:[{size:100,type:'image/jpeg',name:'test.jpg'}]});input.dispatchEvent(new dom.window.Event('change',{bubbles:true}));await new Promise(resolve=>setTimeout(resolve,0));assert.equal(previews,1);assert.match(root.textContent,/Xác nhận thông tin/);root.querySelector('[data-confirm-provider-kyc]').click();await new Promise(resolve=>setTimeout(resolve,0));assert.equal(confirmations,0);assert.match(root.textContent,/Không có tài liệu hoặc hồ sơ xác minh nào được lưu/);});
test('upload utilise chemin opaque, bucket privé, Edge Function et URL signée 300 secondes',async()=>{const calls=[];const client={from(){return{};},auth:{getUser:async()=>({data:{user:{id:'53000000-0000-0000-0000-000000000001'}},error:null})},storage:{from(bucket){calls.push(['bucket',bucket]);return{upload:async(path,file,options)=>{calls.push(['upload',path,options]);return{data:{path},error:null};},createSignedUrl:async(path,seconds)=>{calls.push(['signed',path,seconds]);return{data:{signedUrl:'signed'},error:null};}};}},functions:{invoke:async(name,options)=>{calls.push(['invoke',name,options]);return{data:{},error:null};}},rpc:async name=>({data:name==='get_current_provider_kyc_state'?{provider:{id:'p'},submission:{status:'draft'}}:{},error:null})};const original=globalThis.crypto;Object.defineProperty(globalThis,'crypto',{value:{randomUUID:()=> '53000000-0000-0000-0000-000000000010'},configurable:true});try{const repo=createSupabaseOffersRepository(client);await repo.uploadAndAnalyzeCurrentProviderIdentity({size:10,type:'image/jpeg'});await repo.createCurrentProviderKycSignedUrl('provider/x/identity/front/id.jpg');}finally{Object.defineProperty(globalThis,'crypto',{value:original,configurable:true});}assert.deepEqual(calls[0],['bucket','provider-kyc']);assert.match(calls.find(x=>x[0]==='upload')[1],/^provider\/53000000-0000-0000-0000-000000000001\/identity\/front\/[0-9a-f-]{36}\.jpg$/);assert.equal(calls.find(x=>x[0]==='invoke')[1],'analyze-provider-identity');assert.equal(calls.find(x=>x[0]==='signed')[2],300);});
test('upload HEIC conserve l’original privé et délègue la conversion à Edge',async()=>{const calls=[];const client={from(){return{};},auth:{getUser:async()=>({data:{user:{id:'53000000-0000-0000-0000-000000000001'}},error:null})},storage:{from(){return{upload:async(path,file,options)=>{calls.push(['upload',path,options]);return{data:{path},error:null};}};}},functions:{invoke:async(name,options)=>{calls.push(['invoke',name,options]);return{data:{},error:null};}},rpc:async()=>({data:{submission:{status:'draft'}},error:null})};const original=globalThis.crypto;Object.defineProperty(globalThis,'crypto',{value:{randomUUID:()=> '53000000-0000-0000-0000-000000000010'},configurable:true});try{await createSupabaseOffersRepository(client).uploadAndAnalyzeCurrentProviderIdentity({size:10,type:'image/heic',name:'IMG.HEIC'});}finally{Object.defineProperty(globalThis,'crypto',{value:original,configurable:true});}const upload=calls.find(x=>x[0]==='upload');assert.match(upload[1],/\.heic$/);assert.equal(upload[2].contentType,'image/heic');assert.equal(calls.find(x=>x[0]==='invoke')[2].body.documentPath,upload[1]);});
test('aperçu IA du Provider Test envoie l’image en mémoire sans Storage ni RPC KYC',async()=>{const calls=[];const client={from(){return{};},storage:{from(){throw new Error('Storage must not be used');}},functions:{invoke:async(name,options)=>{calls.push([name,options]);return{data:{extraction},error:null};}},rpc:async()=>{throw new Error('RPC must not be used');}};const file={size:4,type:'image/jpeg',name:'test.jpg',arrayBuffer:async()=>new Uint8Array([255,216,255,217]).buffer};const result=await createSupabaseOffersRepository(client).previewCurrentProviderIdentity(file);assert.equal(calls.length,1);assert.equal(calls[0][0],'analyze-provider-identity');assert.equal(calls[0][1].body.testPreview,true);assert.equal(calls[0][1].body.contentType,'image/jpeg');assert.equal(calls[0][1].body.imageBase64,'/9j/2Q==');assert.equal(result.submission.status,'draft');assert.deepEqual(result.submission.extraction,extraction);});
test('contrat et serveur gardent conversion, erreurs et logs sans données sensibles',async()=>{const [edge,image,contract,migration,config,repository]=await Promise.all(['../supabase/functions/analyze-provider-identity/index.ts','../supabase/functions/_shared/provider-kyc-image.ts','../supabase/functions/_shared/provider-kyc-contract.ts','../supabase/migrations/20260911020000_provider_kyc_ai.sql','../supabase/config.toml','../src/supabase/repositories/offers.js'].map(path=>readFile(new URL(path,import.meta.url),'utf8')));assert.match(config,/\[functions\.analyze-provider-identity\][\s\S]*verify_jwt = true/);assert.match(edge,/OPENAI_API_KEY/);assert.doesNotMatch(edge,/service_role|documentPath.*console|identity_number.*console|console\.(?:info|error)\([^)]*(?:file|image|token)/);assert.match(edge,/store:false/);assert.match(edge,/TEST_PREVIEW_FORBIDDEN/);assert.match(edge,/input\.kind==='test-preview'\)return respond\(origin,200,\{testPreview:true,extraction\}\)/);assert.match(image,/heic-convert/);assert.match(image,/format:'JPEG'/);assert.match(contract,/documentReadable/);assert.match(contract,/confidence/);assert.match(contract,/testPreview/);assert.match(contract,/heic\|heif/);assert.match(migration,/values\('provider-kyc','provider-kyc',false/);assert.match(migration,/image\/heic/);assert.match(migration,/status='draft'/);assert.match(migration,/status='pending_review'/);assert.doesNotMatch(migration,/set status='verified'/);assert.doesNotMatch(repository,/getPublicUrl/);assert.match(repository,/createSignedUrl\(documentPath, 300\)/);});
