import assert from 'node:assert/strict';import{readFile}from'node:fs/promises';import{describe,it}from'node:test';
import{renderProviderDashboard}from'../src/provider/provider-app.js';import{createMockProviderAppRepository}from'../src/provider/provider-repository.js';import{createSupabaseOffersRepository}from'../src/supabase/repositories/offers.js';
describe('Provider App PWA',()=>{
 it('rend le dashboard vietnamien séparé avec statut, offres et actions',async()=>{const repo=createMockProviderAppRepository();const state=await repo.load();const html=renderProviderDashboard(state,{source:'mock'});for(const text of ['HOME AI','Đối tác kỹ thuật','Trạng thái hoạt động','Đang trực tuyến','Sẵn sàng nhận việc','Đề nghị nhiệm vụ','Địa chỉ gần đúng','Chấp nhận','Từ chối','Chế độ demo'])assert.ok(html.includes(text));});
 it('accepte atomiquement dans le mock puis affiche la mission et rend le provider indisponible',async()=>{const repo=createMockProviderAppRepository();const state=await repo.accept('offer-demo-1');assert.equal(state.assignment.id,'mission-demo-1');assert.equal(state.status.available,false);assert.match(renderProviderDashboard(state),/NHIỆM VỤ ĐANG THỰC HIỆN/);});
 it('refuse explicitement une offre sans affecter les autres',async()=>{const repo=createMockProviderAppRepository();const state=await repo.decline('offer-demo-1');assert.deepEqual(state.offers.map(o=>o.id),['offer-demo-2']);assert.equal(state.assignment,null);});
 it('met à jour le dashboard mock complet lors du changement de disponibilité',async()=>{const repo=createMockProviderAppRepository();const state=await repo.setAvailability({online:false,available:false});assert.equal(state.provider.id,'provider-demo');assert.equal(state.status.online,false);assert.equal(state.offers.length,2);});
 it('n’affiche jamais une adresse complète dans une offre avant attribution',()=>{const state={provider:{name:'Minh'},status:{online:true,available:true},offers:[{id:'o1',serviceCategory:'electricity',request:'Test',approximateAddress:'Khu vực Nha Trang',distanceKm:1,etaMinutes:5}],assignment:null};const html=renderProviderDashboard(state);assert.match(html,/Khu vực Nha Trang/);assert.doesNotMatch(html,/12 Nguyễn Trãi/);});
 it('affiche l’adresse complète uniquement dans la mission attribuée',()=>{const state={provider:{name:'Minh'},status:{online:true,available:false},offers:[],assignment:{id:'m1',serviceCategory:'electricity',request:'Test',address:'12 Nguyễn Trãi, Nha Trang',status:'accepted'}};assert.match(renderProviderDashboard(state),/12 Nguyễn Trãi, Nha Trang/);});
 it('utilise uniquement les RPC provider et aucun identifiant provider contrôlé par le client',async()=>{const calls=[];const client={from(){return{}},rpc(name,args){calls.push([name,args]);return Promise.resolve({data:name==='get_current_provider_dashboard'?{provider:{id:'p1'}}:{id:'x'},error:null});}};const repo=createSupabaseOffersRepository(client);await repo.getProviderDashboard();await repo.setProviderAvailability({online:true,available:true,latitude:12.2,longitude:109.2});await repo.declineCurrentProviderOffer('o1');await repo.acceptCurrentProviderOffer('o2');assert.deepEqual(calls.map(c=>c[0]),['get_current_provider_dashboard','set_current_provider_availability','decline_current_provider_offer','accept_current_provider_offer']);assert.equal(calls.some(([,args])=>args&&('provider_id'in args||'assigned_provider_id'in args)),false);});
 it('livre une entrée PWA indépendante du parcours client',async()=>{const [html,manifest,build]=await Promise.all([readFile(new URL('../provider.html',import.meta.url),'utf8'),readFile(new URL('../provider-manifest.webmanifest',import.meta.url),'utf8'),readFile(new URL('../scripts/build.mjs',import.meta.url),'utf8')]);assert.match(html,/provider-root/);assert.doesNotMatch(html,/src\/app\.js/);assert.equal(JSON.parse(manifest).display,'standalone');assert.match(build,/provider\.html/);});
});
