import assert from 'node:assert/strict';import{readFile}from'node:fs/promises';import{describe,it}from'node:test';
const migration=new URL('../supabase/migrations/20260902000800_provider_diagnosis_and_quotes.sql',import.meta.url);
describe('sécurité SQL diagnostic et devis',()=>{
 it('lie la création au provider assigné actif et vérifié',async()=>{const sql=await readFile(migration,'utf8');assert.match(sql,/mission_row\.provider_id is distinct from uid/);assert.match(sql,/profile_has_role\(uid,'provider'\)/);assert.equal((sql.match(/pp\.active and pp\.kyc_status='verified'/g)??[]).length,2);assert.doesNotMatch(sql,/service_role|assigned_provider_id/);});
 it('impose arrived pour v1 et crée une nouvelle version depuis un devis accepté',async()=>{const sql=await readFile(migration,'utf8');assert.match(sql,/mission_row\.status<>'arrived'/);assert.match(sql,/parent_row\.status<>'accepted'/);assert.match(sql,/max\(q\.version\),0\)\+1/);assert.doesNotMatch(sql,/update public\.quotes set diagnosis|update public\.quote_items/);});
 it('ne démarre le travail qu’après acceptation explicite du client',async()=>{const sql=await readFile(migration,'utf8');assert.match(sql,/mission_row\.client_id is distinct from uid/);assert.match(sql,/update public\.quotes set status='accepted'/);assert.match(sql,/update public\.missions set status='in_progress'/);assert.equal((sql.match(/status='in_progress'/g)??[]).length,1);});
 it('valide contenu, montants et garantit les RPC privées',async()=>{const sql=await readFile(migration,'utf8');assert.match(sql,/jsonb_array_length\(new_items\) not between 1 and 20/);assert.match(sql,/\(item->>'amount'\)::bigint < 0/);assert.equal((sql.match(/security definer set search_path = ''/g)??[]).length,3);assert.equal((sql.match(/from public,anon/g)??[]).length,3);assert.equal((sql.match(/to authenticated/g)??[]).length,3);});
 it('s’appuie sur les protections existantes des devis acceptés',async()=>{const secure=await readFile(new URL('../supabase/migrations/20260901000200_secure_home_ai_mvp_schema.sql',import.meta.url),'utf8');assert.match(secure,/An accepted quote is immutable; create a new quote version instead/);assert.match(secure,/Items of an accepted quote are immutable/);});
});
